# Generated by Django 4.0.5 on 2022-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='Gdansk', max_length=50),
            preserve_default=False,
        ),
    ]
