# Generated by Django 4.0.5 on 2022-08-10 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(limit_value=80)]),
        ),
    ]
